server:
  port: 8000
db:
  host: orders-db
  port: 5432
  user: postgres
  pass: postgres
  name: orders_db
kafka:
  publisher:
    interval_ms: 1000
    batch_size: 10
    max_retries: 3
  brokers:
    - "kafka:29092"
redis:
  host: redis
  port: 6379
  channel: "sse-updates"
