// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"orders-service/internal/infrastructure/config"
)

// Injectors from wire.go:

func InitializeApplication() (*Application, error) {
	app := NewConfigApp()
	configConfig := config.MustLoad(app)
	application := NewApplication(configConfig)
	return application, nil
}

// wire.go:

func NewConfigApp() *config.App {
	return config.NewApp("config/config.yaml")
}

type Application struct {
	Config *config.Config
}

func NewApplication(config2 *config.Config) *Application {
	return &Application{
		Config: config2,
	}
}
