apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-service-config
  namespace: microservices
data:
  config.yaml: |
    server:
      port: 8000
    db:
      host: orders-db
      port: 5432
      user: postgres
      pass: postgres
      name: orders_db
    kafka:
      brokers:
        - "kafka:9092" 