apiVersion: batch/v1
kind: Job
metadata:
  name: payments-service-migration
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: payments-service:latest
        imagePullPolicy: Never
        command: ["./api", "migrate"]
        volumeMounts:
        - name: config
          mountPath: "/app/config"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: payments-service-config
      restartPolicy: Never
  backoffLimit: 4 