apiVersion: batch/v1
kind: Job
metadata:
  name: payments-service-migration
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: payments-service:latest
        imagePullPolicy: IfNotPresent
        command: ["./api", "migrate"]
      restartPolicy: Never
  backoffLimit: 4 