apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-service-config
  namespace: microservices
data:
  config.yaml: |
    server:
      port: 8001
    db:
      host: payments-db
      port: 5432
      user: postgres
      pass: postgres
      name: payments_db
    kafka:
      consumer:
        group_id: "payments-service-group"
      brokers:
        - "kafka:9092" 