name: Go CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test orders-service
      run: |
        cd orders-service
        go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out

    - name: Test payments-service
      run: |
        cd payments-service
        go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out 